src/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls'))
]

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostEdit, BlogPostDetail, BlogPostDelete

app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('create/', BlogPostCreate.as_view(), name="create"),
    path('<str:slug>/', BlogPostDetail.as_view(), name="detail"),
    path('edit/<str:slug>/', BlogPostEdit.as_view(), name="edit"),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name="delete")
]

src/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

User = get_user_model()


# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu")

    def get_absolute_url(self):
        return reverse("posts:home")

    @property
    def author_or_default(self):
        return self.author.username if self.author else "Auteur non renseigné."

    class Meta:
        ordering = ["-created_on"]
        verbose_name = "Article"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

src/posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from posts.models import BlogPost


# Create your views here.
class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset

        return queryset.filter(published=True)


class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ["title", "content"]


class BlogPostEdit(UpdateView):
    model = BlogPost
    template_name = "posts/blogpost_edit.html"
    fields = ["title", "content", "published"]


class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"


class BlogPostDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("posts:home")
    context_object_name = "post"

src/posts/templates/posts/blog_post_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Le blog de lotar69</title>
{% endblock %}

{% block content %}

    <h1>Le blog de lotar69</h1>
    {% for post in posts %}
        <article>
            <h2>{{ post.title }}</h2>
            <h5>Publié par <i>{{ post.author.username }}</i></h5> le {{ post.created_on|date:'j F Y' }}</h5>
            <p>{{ post.content|safe|truncatewords:50</p>
        </article>
    {% endfor %}

{% endblock %}

src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Etes vous sur de vouloir supprimer {{ post }} ?</p>
        <!-- post est indiqué car on a indiqué a context_object_name post dans la vue, autrement on aurait indiqué object -->
        <input type="submit" value="Oui, Supprimer">
    </form>
{% endblock %}

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
    <title>Ajouter un article.</title>
{% endblock %}

{% block content %}
    <h1>Ajouter un article.</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Créer">
    </form>
{% endblock %}

src/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block content %}
    <article>
        <h1>{{ post.title }}</h1>
        <div>{{ post.content|linebreaks|safe }}</div>
    </article>
{% endblock %}

src/posts/templates/posts/blogpost_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Editer l'article.</title>
{% endblock %}

{% block content %}
    <h1>Editer l'article.</h1>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Editer">
</form>
{% endblock %}

src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Le blog de lotar69</title>
{% endblock %}

{% block content %}

    <h1>Le blog de lotar69</h1>
    {% for post in posts %}
        <article>
            <h2>{{ post.title }}</h2>
            <div>
                {% if request.user.is_authenticated %}
                <a href="{% url 'posts:edit' slug=post.slug %}">Editer</a>
                <a href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
                {% endif %}
            </div>
            <h5>Publié par <i>{{ post.author_or_default }}</i></h5> le {{ post.created_on|date:'j F Y' }}</h5>
            <p>{{ post.content|safe|truncatewords:50 }}</p>

            <a href="{% url 'posts:detail' slug=post.slug %}">Lire l'article</a>
        </article>
    {% endfor %}

{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}{% endblock %}
</head>
<body>
    <nav>
        <a href="{% url 'posts:home' %}">Accueil</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'posts:create' %}">Ajouter un article</a>
        {% endif %}
    </nav>
    <section id="blog">
        {% block content %}{% endblock %}
    </section>
</body>
</html>